// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVhugsiqS-0e8uZUg7rjIH1yeYUD1V_U',
    appId: '1:178197668801:web:aebb660f93d07354db8540',
    messagingSenderId: '178197668801',
    projectId: 'fixit-f252b',
    authDomain: 'fixit-f252b.firebaseapp.com',
    storageBucket: 'fixit-f252b.appspot.com',
    measurementId: 'G-KYC69T2XJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQxsQEG5hgAX-rw-mjBAx8Nq6lgjikymo',
    appId: '1:178197668801:android:da108cf4c5239b3edb8540',
    messagingSenderId: '178197668801',
    projectId: 'fixit-f252b',
    storageBucket: 'fixit-f252b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu6yIS7VKyAVHH5AFvmOLOpOKqlXgcFrE',
    appId: '1:178197668801:ios:a3ee55ec702fff97db8540',
    messagingSenderId: '178197668801',
    projectId: 'fixit-f252b',
    storageBucket: 'fixit-f252b.appspot.com',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu6yIS7VKyAVHH5AFvmOLOpOKqlXgcFrE',
    appId: '1:178197668801:ios:a5163b80b1eb038bdb8540',
    messagingSenderId: '178197668801',
    projectId: 'fixit-f252b',
    storageBucket: 'fixit-f252b.appspot.com',
    iosBundleId: 'com.example.fixit.RunnerTests',
  );
}
